# Generated by Django 4.1.5 on 2023-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='title', max_length=20),
            preserve_default=False,
        ),
    ]
